version: '3'
services:
  mood:
    build:
      context: ./
    expose:
      - "8505"
    volumes:
      - ./:/app
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mood-ssl.entrypoints=https"
      - "traefik.http.routers.mood-ssl.rule=Host(`mood.koni.monster`)"
      - "traefik.http.routers.mood-ssl.tls=true"
      - "traefik.http.routers.mood-ssl.tls.certresolver=http"
      - "traefik.http.routers.mood-ssl.middlewares=default@file"
      - "traefik.http.routers.mood-ssl.service=mood-ssl"
      - "traefik.http.services.mood-ssl.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true